export const APPWRITE_KEY = process.env.NEXT_APPWRITE_KEY!;
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;
export const APPWRITE_PROJECT_NAME =
  process.env.NEXT_PUBLIC_APPWRITE_PROJECT_NAME!;
export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const APPWRITE_DATABASE = process.env.APPWRITE_DATABASE!;
export const APPWRITE_COLLECTION_USERS = process.env.APPWRITE_COLLECTION_USERS!;
export const APPWRITE_COLLECTION_BANKS = process.env.APPWRITE_COLLECTION_BANKS!;
export const APPWRITE_COLLECTION_TRANSACTIONS =
  process.env.APPWRITE_COLLECTION_TRANSACTIONS!;
